key_columns:
  - canonical_smiles
  - molecular_weight
  - endpoint
  - endpoint_qualifier
  - unit_of_measurement
  - chebi_ligand_function_mode_of_action_id
  - pro_protein_name
  - chembl_target_organism
  - odo_assay_id
  - source

value_column: endpoint_value_nM
numeric_agg: median
concat_sep: ","

